language: node_js
node_js:
- 8.15.1
install:
- yarn
jobs:
  include:
  - stage: test
    script:
    - yarn test
    - yarn scan
    after_success: yarn coverage
env:
  secure: kIZNI1k4uPRQGKXr+Xl7cFhqKt34fKzQRaWJ4GxZoypEB43laSTkgDRjGxLF2QxCFAcueJfIcPQvdfPFyKZco+X8IwMiAY+PY4ufz1nCaMyaDRkEmPKajHistQSzhY9zPUVg3gIM+A2cVPTjQq2lE0SBBWH2oAkylhh+YK7mJTybomlrmD11VWQ1J4V0UKXWDqrRnqbml4xUSNrDjv4ZPusrM7Y4VeOaq4P6DKhu5UyOPEEFyt2+nSlgfyLRsDbzw16ySurHQRKr1En6EQE/W5mM2uoQHavx8UXQ4lsVCgdZlp4m9EOmaGCIvitQUWK0148KkhvXZdTTnaNZvjKPFubC2ySDpyeGdQlkDzSknTca1B4InfkMX1h91geKgpU+Ter0A7aq3EkCMr26D3soZ+2R9WYjoKcfiljRPdpzJQEPY0Lui5zN/tnHuELRF9Wk01lck2Dz+KgJT+16KAw+mrjM6l6uO0Z8aSTCozlZ5ztUIDv+ufZdSwwP8WcMxmdAwdD7TInqHuUSBoY+XyA64JdR++sCkm2H2NyZF35keYLmqZi0CPgOQc5/67l0FdL2kDQpgrIdQblJrg+Gh1stGhT2Vir9IUeXze071D6aJygGl6OJqx95gNKw30ayI0e2qClxtRWktt17oDbd97Ba3vdvLkg1592U6Fn03x0HNgE=
